---
title: "Authorship Abuse & Research Misconduct in Graduate School"
author: "James J. Herlan"
format: 
  revealjs:
    smaller: false
    scrollable: true
    incremental: false
    logo: cuny2.png
    footer: "BIOL Research Ethics Spring 2023"
editor: visual
bibliography: references.bib
---

```{r, include = FALSE}
require(tidyverse)
require(car)
```

#### Disproportionately affects graduate students?

::: incremental
-   Stress of being a graduate student
    -   Relocation
    -   Coursework
-   Naive about authorship credit
    -   Minimal training in authorship ethics
    -   Abuses can erode confidence
-   Imbalance of power
:::

::: {.fragment .fade-up}
Academic advisors and committee members should properly guide and teach research ethics to graduate students.
:::

::: notes
Become subject to exploitation and often lack confidence to assert their credibility as early researchers who can participate in the scientific process.
:::

------------------------------------------------------------------------

::: columns
::: {.column .incremental width="50%"}
#### Science in the United States since WWII

-   Federal funding

-   Science education

-   Technological innovation
:::

::: {.column .incremental width="50%"}
#### [@logan2017]Outcomes for today

-   Employment in scientific fields

-   Number of scientific publications
:::
:::

::: {.fragment .fade-up}
Publishing of scientific articles is a multi-**billion** dollar industry.
:::

::: notes
Increased after World War II

-   Employment in scientific fields

-   Number of scientific publications

Due to increases in

1.  federal funding

2.  science education

3.  advances in technology
:::

------------------------------------------------------------------------

#### Value of publication record and professionalism

::: incremental
-   Validates individual achievement

-   Currency for credit

-   Professors & tenure

-   Graduate students & scholarships
:::

::: notes
Since the 1950s, the number of manuscripts with multiple authors has risen due, in part, to the increase in multidisciplinary research projects; as a consequence, the deleterious effects of abusing authorship credit on graduate students' well-being and valuation in the scientific community needs more discussion.
:::

------------------------------------------------------------------------

::: incremental
-   **Coercion**

    -   Superior intimidates a student

-   **Honorary**

    -   Individual with no contribution

        -   Favor

        -   Solicitation

        -   Reciprocation

-   **Ghost**

    -   Contributor is denied

        -   e.g., student's name is not included
:::

::: notes
-   Coercion is a type of scientific misconduct that often occurs when an individual in a senior academic position intimidates subordinates, such as graduate students, to gain authorship credit

-   Honorary authorship occurs when an individual receives authorship credit without contributing any significant amount of content, like writing or revision, to the manuscript

-   Senior researchers may give authorship credit to colleagues as a favor for reciprocation

-   Honorary authorship can often depreciate the quality of work a graduate student's accomplishes in the manuscript writing process
:::

------------------------------------------------------------------------

#### International Committee of Medical Journals Editors (ICMJE)

"Authorship should be based on...

::: incremental
1.  Substantial contributions to conception and design
2.  Drafting the article or revising it critically for important intellectual merit
3.  Final approval of the version to be published
:::

. . .

No justification of credit

::: incremental
-   Funding

-   Data collection

-   Research supervision
:::

::: notes
-   Most widely accepted guidelines for authorship ethics
:::

------------------------------------------------------------------------

#### International Committee of Medical Journals Editors (ICMJE)

*substantial contribution*?

::: incremental
1.  Authorship credit should be reserved for individuals who helped draft or revise major portions of the manuscript
2.  Must be able to take public responsibility for their contributions to the manuscript
:::

------------------------------------------------------------------------

#### Ecological Society of America (ESA)

::: incremental
1.  Conceived experimental design
2.  Performed methods
3.  Analyzed and interpreted data
4.  Wrote the manuscript
:::

------------------------------------------------------------------------

Survey to first authors of peer reviewed journal articles in ecology, by [@logan2017]

::: incremental
1.  48% - evidence of non-compliance
2.  78% - at least one author non-compliance with ICMJE
3.  **Primary author** - Graduate student & post-doc more likely non-compliance than professors
4.  Probability of non-compliance **increased** with number of co-authors
:::

::: notes
The number of authors on ecological manuscripts has increased over the past several decades as a result of increases in collaboration among scientific research
:::

------------------------------------------------------------------------

#### Solutions

::: incremental

-   Byline system

    -   Ranks and lists contributions of authors with written documents

        -   Verify credit
        -   Confirm contributions
        
::: {.fragment .fade-up}

**Increase the responsibilities of editors and scientific organizations like research universities.**

::: 

::: notes

Elliot et al. (2017) proposed that research teams, such as a laboratory at a university, construct authorship policies with criteria that funding agencies require in grant proposals, although any system would be subject to the biases of people classifying author contribution (Logan et al. 2017).

:::

------------------------------------------------------------------------

#### Conclusion

::: incremental



:::

















